//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo_MarketingTracking.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketingEvent()
        {
            this.User_MarketingEvent = new HashSet<User_MarketingEvent>();
            this.PromotionLog = new HashSet<PromotionLog>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string AndroidUrl { get; set; }
        public Nullable<int> AndroidCount { get; set; }
        public string IosUrl { get; set; }
        public Nullable<int> IosCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_MarketingEvent> User_MarketingEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionLog> PromotionLog { get; set; }
    }
}
